### ISSUE TITLE
Problems assigning the [uid/modelName] property, names that use "-" between words

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [DomDew/strapi-plugin-fuzzy-search#14]
```js
{
  uid: "api::sub-category.sub-category",
  modelName: "sub-category",
}
```

### Error:
```shell
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-categories" does not.
```

###  Dependency versions: package.json

```json
"strapi-plugin-fuzzy-search": "^1.9.3",
"@strapi/strapi": "4.1.11",
```

**Comment by DomDew** [comment]
Hey @ChrisMichaelPerezSantiago, thank you for opening this issue!

Fixed in 1.9.4

@all-contributors please add @ChrisMichaelPerezSantiago  for bug

**Comment by cvcnetworkindia** [comment]
I seem to be still having an issue with this on:
`  "@strapi/strapi": "4.5.3",
    "strapi-plugin-fuzzy-search": "^1.10.2"`

While I'm not getting the RegEx error above, the endpoint (I'm using GraphQL) is not returning results for models with '-' in their names.

Here's my plugin.js file:

```
  "fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: "api::product-variant.product-variant",
          modelName: "product-variant",
          transliterate: false,
          queryConstraints: {
            where: {
              $and: [
                {
                  publishedAt: { $notNull: true },
                },
              ],
            },
          },
          fuzzysortOptions: {
            characterLimit: 300,
            limit: 50,
            keys: [
              {
                name: "ModelNumber",
                weight: 100,
              },
              {
                name: "CatCode",
                weight: 50,
              },
              {
                name: "Description",
                weight: -400,
              },
            ],
          },
        },
        {
          uid: "api::product.product",
          modelName: "product",
          transliterate: false,
          queryConstraints: {
            where: {
              $and: [
                {
                  publishedAt: { $notNull: true },
                },
              ],
            },
          },
          fuzzysortOptions: {
            characterLimit: 300,
            threshold: -400,
            limit: 50,
            keys: [
              {
                name: "ProductName",
                weight: 100,
              },
              {
                name: "ProductDescription",
                weight: -400,
              },
              {
                name: "ProductAttributes",
                weight: -200,
              },
              {
                name: "Features",
                weight: -200,
              },
            ],
          },
        },
        {
          uid: "api::blog.blog",
          modelName: "blog",
          transliterate: false,
          queryConstraints: {
            where: {
              $and: [
                {
                  publishedAt: { $notNull: true },
                },
              ],
            },
          },
          fuzzysortOptions: {
            characterLimit: 300,
            threshold: -300,
            limit: 50,
            keys: [
              {
                name: "Title",
                weight: 100,
              },
              {
                name: "Quote",
                weight: -100,
              },
              {
                name: "Body",
                weight: -300,
              },
            ],
          },
        },
        {
          uid: "api::case-study.case-study",
          modelName: "case-study",
          transliterate: false,
          queryConstraints: {
            where: {
              $and: [
                {
                  publishedAt: { $notNull: true },
                },
              ],
            },
          },
          fuzzysortOptions: {
            characterLimit: 300,
            limit: 50,
            keys: [
              {
                name: "Title",
                weight: 100,
              },
              {
                name: "clientName",
                weight: -70,
              },
              {
                name: "shortDescription",
                weight: -100,
              },
              {
                name: "keyFact",
                weight: -200,
              },
            ],
          },
        },
      ],
    },
  },
```

I'm getting results for product and blog but not for product-variant and case-study.
